### ISSUE TITLE
is everything in this repo under the Apache license?

### ISSUE THREAD

**Issue by cartazio** [seanmcl/imogen#1]
the root directory says apache, but certain subtrees i'd like to work through understanding seem to have gpl licenses ?

**Comment by seanmcl** [comment]
Hi.  

Apache is fine.  I'll change any license that is more restrictive if you just point me to the place.

Best,

Sean

**Comment by cartazio** [comment]
wonderful! in the haskell and sml sub directories its currently gpl, and seemingly its a code dump of exclusively your own code so you can change the license at your own whim? :) 

https://github.com/seanmcl/imogen/blob/master/src/main/haskell/imogen/LICENSE and https://github.com/seanmcl/imogen/blob/master/src/main/sml/LICENSE 

are there other prover code bases  that are tractable to read through that you can point me at? (i'm on a little bit of a linear logic bender with my own flavor, and Lin logic inspired methods are easier to stumble into actual code for)

**Comment by cartazio** [comment]
(to be clear: this one is readable, just wondering if theres other good ones to also look at)

**Comment by cartazio** [comment]
let me know how i can help, thx!

**Comment by cartazio** [comment]
let me know how i can help, thx!

**Comment by seanmcl** [comment]
I replaced them all with apache.  Sorry for the delay.

**Comment by cartazio** [comment]
WOnderful! this is great.

are there any other OSS solvers/provers you'd recommend looking at?
